// ERROR SIGNIN USER
const TITLE_AUTHENTICATION_ERROR = "Error na autenticação";
const DESCRIPTION_AUTHENTICATION_ERROR =
  "Ocorreu um erro ao fazer login, cheque as credenciais!";

// ERROR MESSAGES VALIDATION
const REQUIRED_EMAIL_MESSAGE_ERROR = "E-mail obrigatório";
const EMAIL_MESSAGE_ERROR = "Digite um -email válido";
const REQUIRED_PASSWORD_MESSAGE_ERROR = "Senha obrigatoria";

export {
  TITLE_AUTHENTICATION_ERROR,
  DESCRIPTION_AUTHENTICATION_ERROR,
  REQUIRED_EMAIL_MESSAGE_ERROR,
  EMAIL_MESSAGE_ERROR,
  REQUIRED_PASSWORD_MESSAGE_ERROR,
};
